USE [master]
GO

/****** Object:  Database [MoneyExchange]    Script Date: 2025/02/23 10:21:22 ******/
CREATE DATABASE [MoneyExchange]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoneyExchange', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MoneyExchange.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoneyExchange_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MoneyExchange_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoneyExchange].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoneyExchange] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoneyExchange] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoneyExchange] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoneyExchange] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoneyExchange] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoneyExchange] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoneyExchange] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoneyExchange] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoneyExchange] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoneyExchange] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoneyExchange] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoneyExchange] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoneyExchange] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoneyExchange] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoneyExchange] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoneyExchange] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoneyExchange] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoneyExchange] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoneyExchange] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoneyExchange] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoneyExchange] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoneyExchange] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoneyExchange] SET RECOVERY FULL 
GO

ALTER DATABASE [MoneyExchange] SET  MULTI_USER 
GO

ALTER DATABASE [MoneyExchange] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoneyExchange] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoneyExchange] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoneyExchange] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoneyExchange] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoneyExchange] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MoneyExchange] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoneyExchange] SET  READ_WRITE 
GO